# Default values for key.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
    repository: marqub/go-service
    tag: dev
    pullPolicy: Always  
service:
    name: go-service
    type: NodePort
    externalPort: 8080
    internalPort: 8080